// <auto-generated />
namespace issConstructions.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ConM20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConM20));
        
        string IMigrationMetadata.Id
        {
            get { return "202207160420394_ConM20"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
